name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean compile

      - name: Run tests
        run: mvn test

      - name: Package JAR
        run: mvn package -DskipTests

      - name: Run JAR as test
        run: java -jar target/LeftLang-1.0-SNAPSHOT.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: LeftLang
          path: target/*.jar
